from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from django.conf import settings

import machiavelli.views as views

app_name = 'machiavelli'

# Help context
help_context = {
	'contact_email': getattr(settings, 'CONTACT_EMAIL', ''),
	'forum_url': '/forum',
}

urlpatterns = [
	# Help URLs
	path('help/', cache_page(60*60)(TemplateView.as_view(
		template_name='machiavelli/help/index.html',
		extra_context=help_context
	)), name='help_index'),
	path('help/contribute', cache_page(60*60)(TemplateView.as_view(
		template_name='machiavelli/help/contribute.html',
		extra_context=help_context
	)), name='help_contribute'),
	
	# Existing URLs
	path('', views.SummaryView.as_view(), name='summary'),
	path('games/all_finished',
		views.AllFinishedGamesList.as_view(),
		name="games_all_finished"), 
	path('games/finished',
		views.MyFinishedGamesList.as_view(),
		name="games_my_finished"), 
	path('games/other_active',
		views.OtherActiveGamesList.as_view(),
		name="games_other_active"), 
	path('games/my_active',
		views.MyActiveGamesList.as_view(),
		name="games_my_active"), 
	path('games/joinable',
		views.JoinableGamesList.as_view(),
		name="games_joinable"), 
	path('games/pending',
		views.PendingGamesList.as_view(),
		name='games_pending'),
	path('revolutions',
		views.RevolutionList.as_view(),
		name='revolution_list'),
	path('ranking',
		views.HallOfFameView.as_view(),
		name='hall_of_fame'),
	re_path(r'^ranking/(?P<key>[-\w]+)/(?P<val>[-\w]+)$', views.ranking, name='ranking'),
	re_path(r'^overthrow/(?P<revolution_id>\d+)$',
		views.OverthrowView.as_view(),
		name='overthrow'),
	re_path(r'^undo_overthrow/(?P<revolution_id>\d+)$',
		views.UndoOverthrowView.as_view(),
		name='undo_overthrow'),
	path('new_game',
		views.CreateGameView.as_view(),
		name='new_game'),
	path('new_team_game',
		views.CreateTeamGameView.as_view(),
		name='new_team_game'),
	re_path(r'^game/(?P<slug>[-\w]+)/invite$',
		views.GameInvitationView.as_view(),
		name='invite_users'),
	re_path(r'^game/(?P<slug>[-\w]+)/join$',
		views.JoinGameView.as_view(),
		name='join_game'),
	re_path(r'^game/(?P<slug>[-\w]+)/public$',
		views.MakeGamePublic.as_view(),
		name='make_public'),
	re_path(r'^game/(?P<slug>[-\w]+)/leave$',
		views.LeaveGameView.as_view(),
		name='leave_game'),
	re_path(r'^game/(?P<slug>[-\w]+)/log$', views.logs_by_game, name='game_log'),
	re_path(r'^game/(?P<slug>[-\w]+)/areas$',
		views.GameAreaListView.as_view(),
		name='gamearea_list'),
	re_path(r'^game/(?P<slug>[-\w]+)/turn$',
		views.TurnLogListView.as_view(),
		name='turn_log_list'),
	re_path(r'^game/(?P<slug>[-\w]+)/excommunicate/(?P<player_id>\d+)$',
		views.ExcommunicationView.as_view(action="punish"),
		name='excommunicate'),
	re_path(r'^game/(?P<slug>[-\w]+)/forgive/(?P<player_id>\d+)$',
		views.ExcommunicationView.as_view(action="forgive"),
		name='forgive_excommunication'),
	re_path(r'^game/(?P<slug>[-\w]+)/lend/(?P<player_id>\d+)$',
		views.GiveMoneyView.as_view(),
		name='lend'),
	re_path(r'^game/(?P<slug>[-\w]+)/borrow$',
		views.BorrowMoneyView.as_view(),
		name='borrow_money'),
	re_path(r'^game/(?P<slug>[-\w]+)/repay/(?P<credit_id>\d+)$',
		views.ReturnMoneyView.as_view(),
		name='return_credit'),
	re_path(r'^game/(?P<slug>[-\w]+)/assassination$',
		views.AssassinationView.as_view(),
		name='assassination'),
	re_path(r'^game/(?P<slug>[-\w]+)/confirm_orders$',
		views.ConfirmOrdersView.as_view(),
		name='confirm_orders'),
	re_path(r'^game/(?P<slug>[-\w]+)/undo$',
		views.UndoActionsView.as_view(),
		name='undo_actions'),
	re_path(r'^game/(?P<slug>[-\w]+)/surrender$',
		views.SurrenderView.as_view(),
		name='surrender'),
	re_path(r'^game/(?P<slug>[-\w]+)/delete_order/(?P<order_id>\d+)$',
		views.DeleteOrderView.as_view(),
		name='delete_order'),
	re_path(r'^game/(?P<slug>[-\w]+)/expenses$',
		views.ExpenseCreateView.as_view(),
		name='expenses'),
	re_path(r'^game/(?P<slug>[-\w]+)/undo_expense/(?P<expense_id>\d+)$',
		views.ExpenseDeleteView.as_view(),
		name='undo_expense'),
	re_path(r'^game/(?P<slug>[-\w]+)/taxation$', views.taxation, name='taxation'),
	re_path(r'^game/(?P<slug>[-\w]+)/whisper$',
		views.WhisperCreateView.as_view(),
		name='new_whisper'),
	re_path(r'^game/(?P<slug>[-\w]+)/whisper_list$',
		views.WhisperListView.as_view(),
		name='whisper_list'),
	re_path(r'^game/(?P<slug>[-\w]+)/journal$',
		views.EditJournalView.as_view(),
		name='edit_journal'),
	re_path(r'^game/(?P<slug>[-\w]+)/team_messages$',
		views.TeamMessageListView.as_view(),
		name='team_messages'),
	re_path(r'^game/(?P<slug>[-\w]+)/report$',
		views.ErrorReportCreateView.as_view(),
		name='new_report'),
	re_path(r'^game/(?P<slug>[-\w]+)$',
		views.GameRouter.as_view(),
		name='show_game'),
]

